<?php
/**
 * @file
 * Handles the creation and display of binary_object Islandora objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_binary_object_menu() {
  $items = array();
  $items['admin/islandora/tools/binary-object-storage'] = array(
    'title' => 'Binary Object Collection',
    'description' => 'Configure settings for Islandora Binary Object',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_binary_object_admin'),
    'file' => 'includes/admin.inc',
  );
  $items['admin/islandora/tools/binary-object-storage/delete-association/%'] = array(
    'title' => 'Delete Binary Object Association',
    'description' => 'Confirm form for deleting a thumbnail association',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'islandora_binary_object_delete_association_form',
      4,
      5,
    ),
    'file' => 'includes/admin.inc',
  );
  return $items;
}
/**
 * Implements hook_theme().
 */
function islandora_binary_object_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_binary_object' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-binary-object',
      'pattern' => 'islandora_binary_object__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_binary_object_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_binary_object');
  $islandora_path = drupal_get_path('module', 'islandora');
  // Binary Object Content Model.
  $binary_object_content_model = $connection->repository->constructObject('islandora:binaryObjectCModel');
  $binary_object_content_model->owner = 'fedoraAdmin';
  $binary_object_content_model->label = 'Islandora Binary Object Content Model';
  $binary_object_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $binary_object_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_binary_object_ds_composite_model.xml", FALSE);
  $binary_object_content_model->ingestDatastream($datastream);
  // Image Collection.
  $binary_object_collection = $connection->repository->constructObject('islandora:binary_object_collection');
  $binary_object_collection->owner = 'fedoraAdmin';
  $binary_object_collection->label = 'Binary Object Collection';
  $binary_object_collection->models = 'islandora:collectionCModel';
  $binary_object_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $binary_object_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_binary_object_collection_policy.xml", FALSE);
  $binary_object_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $binary_object_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $binary_object_collection->ingestDatastream($datastream);
  return array(
    'islandora_binary_object' => array(
      'title' => 'Islandora Binary Object',
      'objects' => array(
        $binary_object_content_model,
        $binary_object_collection,
      ),
    ),
  );
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_binary_object_xml_form_builder_form_associations() {
  return array(
    'islandora_binary_object_mods_form' => array(
      'content_model' => 'islandora:binaryObjectCModel',
      'form_name' => 'Binary Object MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
  );
}


/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_binary_object_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_binary_object');
  return array(
    'Binary Object MODS form' => array(
      'form_file' => "$module_path/xml/islandora_binary_object_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_binary_object_islandora_binaryObjectCModel_islandora_ingest_steps() {
  return array(
    'islandora_binary_object' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_binary_object_upload_form',
      'module' => 'islandora_binary_object',
      'file' => 'includes/binary_object_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_binary_object_islandora_binaryObjectCModel_islandora_view_object(AbstractObject $object) {
  return array(
    // XXX: Because islandora_as_renderable_array isn't the best we are going to
    // wrap this in an array.
    '' => array(
      array(
        '#theme' => 'islandora_binary_object',
        '#islandora_object' => $object,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_binary_object_islandora_binaryObjectCModel_islandora_derivative() {
  return array(
    array(
      'source_dsid' => NULL,
      'destination_dsid' => 'TN',
      'weight' => '0',
      'function' => array(
        'islandora_binary_object_create_thumbnail',
      ),
      'file' => drupal_get_path('module', 'islandora_binary_object') . '/includes/derivatives.inc',
    ),
  );
}
