<?php

/**
 * @file
 * Hook implementations.
 */

/**
 * Implements hook_islandora_importer().
 */
function islandora_binary_object_zip_importer_islandora_importer() {
  // XXX: Using menu_get_item will recurse through itself from here, so we're
  // manually parsing it here.
  $path_parts = explode('/', current_path());
  if (count($path_parts) >= 3) {
    $collection = islandora_object_load($path_parts[2]);
    if ($collection && in_array('islandora:collectionCModel', $collection->models)) {
      $policy = new CollectionPolicy($collection['COLLECTION_POLICY']->content);
      if (in_array('islandora:binaryObjectCModel', array_keys($policy->getContentModels()))) {
        return array(
          'binary_object_importer' => array(
            'title' => t('Binary Object Zip Importer'),
            'class' => 'BinaryObjectZipBatchImporter',
          ),
        );
      }
    }
  }
}
