<?php
/**
 * @file
 * management of custom blocks for digital.lib.utk.edu d7/islandora instance
 */

function utk_lib_digital_custom_block_info()
{
    $blocks['utk_lib_digital_custom_header'] = array(
        'info' => t('UTK Digital Collections Header'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['utk_lib_digital_custom_banner'] = array(
        'info' => t('UTK Digital Collections Banner'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function utk_lib_digital_custom_block_view($delta = '')
{
    $block = array();
    module_load_include('inc', 'islandora', 'includes/utilities');
    $arrowmont = array("curriculum", "arrpgimg", "arrscrap", "arrsimple", "sturley", "3d");
    $gsmrc = array("roth", "50yrcove", "colloquy", "webster", "kintner", "adams", "pcard00", "smhc", "rfj", "thompson", "wcc", "wderfilms", "derris");

    $is_a_introduction = drupal_match_path(drupal_lookup_path('alias', current_path()), '*collection');
    $parsed_request = explode('/', $_SERVER['REQUEST_URI']);

    $pid = urldecode(end($parsed_request));
    $member_of = "";
    // If not an introduction page determine the PID
    if (!$is_a_introduction) {
        $object = islandora_object_load($pid);
        // If an object find the parent
        if ($object) {
            $member_of = utk_lib_digital_custom_parent($pid);
        }
    } else {
        // Remove the collection string from mugwumpcollection to mugwump
        $pid = str_replace("collection", "", $pid);

        // Determined if collection belongs to naming exception collections
        if (in_array($pid, $arrowmont)) {
            $pid = "arrowmont:" . $pid;
        } elseif (in_array($pid, $gsmrc)) {
            $pid = "gsmrc:" . $pid;
        } else {
            $pid = "collections:" . $pid;
        }
        $object = islandora_object_load($pid);
        $member_of = utk_lib_digital_custom_parent($pid);
    }

    // firing the 2 blocks
    switch ($delta) {
        case 'utk_lib_digital_custom_header':
            $block['content'] = utk_lib_digital_custom_header();
            break;
        case 'utk_lib_digital_custom_banner':
            if ($member_of != "") {
                $block['content'] = utk_lib_digital_custom_banner($member_of);
            }
            break;
    }
    return $block;
}

function utk_lib_digital_custom_header()
{
    return '
            <div class="utk-lib-digital--header">
              <div class="utk-lib-digital--header--container">
                  <div class="container">
                      <a class="utk-lib-digital--header--title"
                         href="https://digital.lib.utk.edu">
                        <h1>' . variable_get('site_name', 'Default') . '</h1>
                      </a>
                      <ul class="utk-lib-digital--header--menu">
                        <li><a href="https://digital.lib.utk.edu">Home</a></li>
                        <li><a href="https://digital.lib.utk.edu/collections/about">About</a></li>
                        <li><a href="https://digital.lib.utk.edu/collections/user">User Login</a></li>
                      </ul>
                  </div>
              </div>
            </div>
            ';
}

function utk_lib_digital_custom_banner($pidd)
{
    $collection = utk_lib_digital_get_collection_basics($pidd);

    $image = 'https://digital.lib.utk.edu/iiif/2/collections~islandora~object~' . $pidd . '~datastream~FEATURED~view/full/523,/0/default.jpg';
    $title = $collection->data->fgs_label_s;
    $abstract = $collection->data->utk_mods_abstract_ms[0];

    //Postcards from the Great Smoky Mountains

    return '
            <div class="utk-lib-digital--banner" id="utk-digital-banner-' . str_replace(':', '-', $pidd) . '">
                <a href="/collections/islandora/object/' . $pidd . '">
                    <div class="utk-lib-digital--banner--inner">
                        <div class="utk-lib-digital--banner--info">
                            <span class="utk-lib-digital--banner--info--title">
                                <strong>' . $title . '</strong>
                            </span>
                            <span class="utk-lib-digital--banner--info--abstract">' . $abstract . '</span>
                        </div>
                        <img alt="' . $title . ' collection banner image" src="' . $image . '" />
                    </div>
                    <div class="utk-lib-digital--banner--background-wrap">
                        <div class="utk-lib-digital--banner--background" style="background-image: url(' . $image . ')"></div>
                    </div>
                </a>
            </div>
           ';
}


function utk_lib_digital_get_collection_basics($islandora_pid)
{
    $json = file_get_contents('https://www.lib.utk.edu/wp-json/dc/pid/' . $islandora_pid);
    return json_decode($json);
}

function utk_lib_digital_custom_featured_image($islandora_pid)
{
    $json = file_get_contents('https://www.lib.utk.edu/wp-json/dc/pid/' . $islandora_pid);
    $featured = json_decode($json);
    $alt = $featured->data->fgs_label_s;
    $src = 'https://digital.lib.utk.edu/iiif/2/collections~islandora~object~' . $islandora_pid . '~datastream~FEATURED~view/full/322,/0/default.jpg';
    $output = '<img src="' . $src . '" alt="' . $alt . '" />';
    return $output;
}

function utk_lib_digital_custom_parent($pid_to_check)
{
    $ismemberofcollection = "";
    module_load_include('inc', 'islandora', 'includes/utilities');
    // Handle errors when fetching the JSON from WP site.
    set_error_handler(
        function ($severity, $message, $file, $line) {
            throw new ErrorException($message, $severity, $severity, $file, $line);
        }
    );

    $object_to_check = islandora_object_load($pid_to_check);

    if ($object_to_check) {
        // Wrapping in a try catch to fetch parent recursively
        try {
            $ismemberofcollection = $pid_to_check;
            $json = file_get_contents('https://www.lib.utk.edu/wp-json/dc/pid/' . $pid_to_check);
            $json_check = json_decode($json);
            if (json_decode($json) === null) {
                throw new Exception('JSON is empty');
            }
            if (!isset($json_check->data->utk_fedora_datastream_version_FEATURED_SIZE_ms)) {
                throw new Exception('JSON FEATURED is not set');
            }

        } catch (Exception $e) {
            // When there's an error recursively check for the parent
            // Parent(s) of this PID
            // If at the highest parent don't do anything.
            if (($pid_to_check !== "islandora:root") && ($pid_to_check !== "digital:collections")) {
                $ismemberofcollection = $object_to_check->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection')[0]['object']['value'];
                $ismemberofcollection = utk_lib_digital_custom_parent($ismemberofcollection);
            } else {
                $ismemberofcollection = "";
            }
            // For Debugging
            // echo $e->getMessage();
        }
        restore_error_handler();
    }
    return $ismemberofcollection;
}
